In [ ]:
import pandas as pd
from google.colab import drive
drive.mount('/content/drive', force_remount = True)
path = "drive/My Drive/Colab Notebooks/Social_Network.csv"
df = pd.read_csv(path)
df

Mounted at /content/drive


User ID  Gender  Age  EstimatedSalary Purchased
0    15668575       0   26            43000        No
1    15603246       0   27            57000        No
2    15598044       0   27            84000        No
3    15727311       0   35            65000        No
4    15570769       0   26            80000        No
..        ...     ...  ...              ...       ...
395  15672330       1   47            34000       Yes
396  15807837       1   48            33000       Yes
397  15592570       1   47            23000       Yes
398  15635893       1   60            42000       Yes
399  15706071       1   51            23000       Yes

[400 rows x 5 columns]

In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report, roc_curve, auc
import matplotlib.pyplot as plt

In [ ]:
df.dropna(inplace = True)

In [ ]:
x=df.iloc[:, 1:-1].values
print(x[0:10])

[[    0    26 43000]
 [    0    27 57000]
 [    0    27 84000]
 [    0    35 65000]
 [    0    26 80000]
 [    0    26 52000]
 [    0    21 16000]
 [    0    28 44000]
 [    0    33 28000]
 [    0    26 72000]]


In [ ]:
df['Purchased']= df['Purchased'].replace({'T':1, 'F':0})
df['Purchased']

0       No
1       No
2       No
3       No
4       No
      ... 
395    Yes
396    Yes
397    Yes
398    Yes
399    Yes
Name: Purchased, Length: 400, dtype: object

In [ ]:
y = df.iloc[:, -1].values
print(y[0:10])

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'No']


In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25, random_state=1)

In [ ]:
print(x_train)

[[     0     30  79000]
 [     1     49  89000]
 [     1     35  53000]
 [     0     22  63000]
 [     0     46  96000]
 [     0     47 107000]
 [     0     34  72000]
 [     1     38  71000]
 [     0     48 138000]
 [     1     38  61000]
 [     0     37  57000]
 [     1     57  60000]
 [     0     44  39000]
 [     1     38  51000]
 [     1     28  79000]
 [     0     35  60000]
 [     0     54  26000]
 [     1     35  75000]
 [     1     23  63000]
 [     1     47  34000]
 [     0     29  83000]
 [     1     21  72000]
 [     1     60  34000]
 [     1     49  65000]
 [     1     35  91000]
 [     0     34  25000]
 [     0     41  72000]
 [     0     33  51000]
 [     0     48  30000]
 [     1     51  23000]
 [     0     49  36000]
 [     0     52  38000]
 [     1     46 117000]
 [     0     45 131000]
 [     1     42 149000]
 [     0     59  88000]
 [     0     59  42000]
 [     1     25  33000]
 [     0     46  74000]
 [     1     36 118000]
 [     0     27  54000]
 [     1     22 

In [ ]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)

KNeighborsClassifier()

In [ ]:
# roc curve and auc
from sklearn.datasets import make_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve
from sklearn.metrics import roc_auc_score
from matplotlib import pyplot
# generate 2 class dataset
X, y = make_classification(n_samples=1000, n_classes=2, random_state=1)
# split into train/test sets
trainX, testX, trainy, testy = train_test_split(X, y, test_size=0.5, random_state=2)
# generate a no skill prediction (majority class)
ns_probs = [0 for _ in range(len(testy))]
# fit a model
model = LogisticRegression(solver='lbfgs')
model.fit(trainX, trainy)
# predict probabilities
lr_probs = model.predict_proba(testX)
# keep probabilities for the positive outcome only
lr_probs = lr_probs[:, 1]
# calculate scores
ns_auc = roc_auc_score(testy, ns_probs)
lr_auc = roc_auc_score(testy, lr_probs)
# summarize scores
print('No Skill: ROC AUC=%.3f' % (ns_auc))
print('Logistic: ROC AUC=%.3f' % (lr_auc))
# calculate roc curves
ns_fpr, ns_tpr, _ = roc_curve(testy, ns_probs)
lr_fpr, lr_tpr, _ = roc_curve(testy, lr_probs)
# plot the roc curve for the model
pyplot.plot(ns_fpr, ns_tpr, linestyle='--', label='No Skill')
pyplot.plot(lr_fpr, lr_tpr, marker='.', label='Logistic')
# axis labels
pyplot.xlabel('False Positive Rate')
pyplot.ylabel('True Positive Rate')
# show the legend
pyplot.legend()
# show the plot
pyplot.show()

In [ ]:
# f. Analyse the performance of the classifier with various performance measures such as
# confusion matrix, accuracy, recall, precision, specificity, f-score, Receiver operating
# characteristic (ROC) curve and Area Under Curve (AUC) score. g. Perform feature scaling on independent variables and analyse the performance
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, recall_score, precision_score, roc_curve, auc
from sklearn.preprocessing import StandardScaler

# generate some example data
X, y = make_classification(n_samples=1000, n_features=10, n_classes=2, random_state=42)

# split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# perform feature scaling on the independent variables
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# train a logistic regression classifier
clf = LogisticRegression(random_state=42)
clf.fit(X_train, y_train)

# make predictions on the test set
y_pred = clf.predict(X_test)

# calculate the confusion matrix
cm = confusion_matrix(y_test, y_pred)

# calculate the accuracy
accuracy = accuracy_score(y_test, y_pred)

# calculate the recall
recall = recall_score(y_test, y_pred)

# calculate the precision
precision = precision_score(y_test, y_pred)

# calculate the specificity
specificity = cm[0, 0] / (cm[0, 0] + cm[0, 1])

f_score = 2 * (precision * recall) / (precision + recall)

fpr, tpr, thresholds = roc_curve(y_test, clf.predict_proba(X_test)[:,1])
auc_score = auc(fpr, tpr)

print("Confusion Matrix:\n", cm)
print("Accuracy:", accuracy)
print("Recall:", recall)
print("Precision:", precision)
print("Specificity:", specificity)
print("F-score:", f_score)
print("AUC score:", auc_score)



In [ ]:
# h. Change the value of K in KNN with 5,7,9,11 and tabulate the various TP, TN, accuracy, f-score and AUC score obtained. K value TP TN Accuracy f-score AUC score
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score

X, y = make_classification(n_samples=1000, n_features=20, random_state=42)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


k_values = [5, 7, 9, 11]

tp_list = []
tn_list = []
accuracy_list = []
f_score_list = []
auc_list = []

for k in k_values:
    knn = KNeighborsClassifier(n_neighbors=k)
    knn.fit(X_train, y_train)
    
    y_pred = knn.predict(X_test)
    tn, fp, fn, tp = confusion_matrix(y_test, y_pred).ravel()
    tp_list.append(tp)
    tn_list.append(tn)
    accuracy_list.append(accuracy_score(y_test, y_pred))
    f_score_list.append(f1_score(y_test, y_pred))
    auc_list.append(roc_auc_score(y_test, y_pred))
    
print("K value\tTP\tTN\tAccuracy\tF-score\tAUC score")
for i in range(len(k_values)):
    print(f"{k_values[i]}\t{tp_list[i]}\t{tn_list[i]}\t{accuracy_list[i]:.2f}\t{f_score_list[i]:.2f}\t{auc_list[i]:.2f}")


In [ ]:
# i. Analyse for which K value, the classification algorithm provides better performance.
import matplotlib.pyplot as plt

plt.figure(figsize=(8, 6))
plt.plot(k_values, accuracy_list, label='Accuracy')
plt.plot(k_values, f_score_list, label='F-score')
plt.plot(k_values, auc_list, label='AUC score')
plt.legend()
plt.xlabel('K value')
plt.ylabel('Performance metric')
plt.show()
max_accuracy = max(accuracy_list)
max_accuracy_k = k_values[accuracy_list.index(max_accuracy)]
print(f"Maximum accuracy: {max_accuracy:.2f} (K={max_accuracy_k})")

max_f_score = max(f_score_list)
max_f_score_k = k_values[f_score_list.index(max_f_score)]
print(f"Maximum F-score: {max_f_score:.2f} (K={max_f_score_k})")

max_auc = max(auc_list)
max_auc_k = k_values[auc_list.index(max_auc)]
print(f"Maximum AUC score: {max_auc:.2f} (K={max_auc_k})")
